services:
  - type: web
    name: buds-klicker
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: PORT
        value: 3000 